const sampleListings = [
  {
    id: 1,
    name: "Amit Sharma",
    bloodGroup: "A+",
    region: "North",
    district: "District 1",
    status: "AVAILABLE",
    mobile: "9876543210",
  },
  {
    id: 2,
    name: "Priya Singh",
    bloodGroup: "O-",
    region: "South",
    district: "District 2",
    status: "UNAVAILABLE",
    mobile: "9876543211",
  },
  {
    id: 3,
    name: "Rahul Verma",
    bloodGroup: "B+",
    region: "East",
    district: "District 3",
    status: "AVAILABLE",
    mobile: "9876543212",
  },
  {
    id: 4,
    name: "Neha Patil",
    bloodGroup: "AB-",
    region: "West",
    district: "District 1",
    status: "UNAVAILABLE",
    mobile: "9876543213",
  },
  {
    id: 5,
    name: "Suresh Kumar",
    bloodGroup: "O+",
    region: "North",
    district: "District 2",
    status: "AVAILABLE",
    mobile: "9876543214",
  },
  {
    id: 6,
    name: "Ananya Roy",
    bloodGroup: "A-",
    region: "South",
    district: "District 3",
    status: "UNAVAILABLE",
    mobile: "9876543215",
  },
  {
    id: 7,
    name: "Vikram Das",
    bloodGroup: "B-",
    region: "East",
    district: "District 1",
    status: "AVAILABLE",
    mobile: "9876543216",
  },
  {
    id: 8,
    name: "Meera Joshi",
    bloodGroup: "AB+",
    region: "West",
    district: "District 2",
    status: "UNAVAILABLE",
    mobile: "9876543217",
  },
  {
    id: 9,
    name: "Arjun Kapoor",
    bloodGroup: "A+",
    region: "North",
    district: "District 3",
    status: "AVAILABLE",
    mobile: "9876543218",
  },
  {
    id: 10,
    name: "Kiran Rao",
    bloodGroup: "O-",
    region: "South",
    district: "District 1",
    status: "UNAVAILABLE",
    mobile: "9876543219",
  },
  {
    id: 11,
    name: "Rohit Jain",
    bloodGroup: "B+",
    region: "East",
    district: "District 2",
    status: "AVAILABLE",
    mobile: "9876543220",
  },
  {
    id: 12,
    name: "Sakshi Verma",
    bloodGroup: "AB-",
    region: "West",
    district: "District 3",
    status: "UNAVAILABLE",
    mobile: "9876543221",
  },
  {
    id: 13,
    name: "Rajesh Mehta",
    bloodGroup: "O+",
    region: "North",
    district: "District 1",
    status: "AVAILABLE",
    mobile: "9876543222",
  },
  {
    id: 14,
    name: "Sonal Patel",
    bloodGroup: "A-",
    region: "South",
    district: "District 2",
    status: "UNAVAILABLE",
    mobile: "9876543223",
  },
  {
    id: 15,
    name: "Vivek Singh",
    bloodGroup: "B-",
    region: "East",
    district: "District 3",
    status: "AVAILABLE",
    mobile: "9876543224",
  },
  {
    id: 16,
    name: "Riya Chaudhary",
    bloodGroup: "AB+",
    region: "West",
    district: "District 1",
    status: "UNAVAILABLE",
    mobile: "9876543225",
  },
  {
    id: 17,
    name: "Siddharth Kumar",
    bloodGroup: "A+",
    region: "North",
    district: "District 2",
    status: "AVAILABLE",
    mobile: "9876543226",
  },
  {
    id: 18,
    name: "Aisha Khan",
    bloodGroup: "O-",
    region: "South",
    district: "District 3",
    status: "UNAVAILABLE",
    mobile: "9876543227",
  },
  {
    id: 19,
    name: "Amitabh Das",
    bloodGroup: "B+",
    region: "East",
    district: "District 1",
    status: "AVAILABLE",
    mobile: "9876543228",
  },
  {
    id: 20,
    name: "Sneha Agarwal",
    bloodGroup: "AB-",
    region: "West",
    district: "District 2",
    status: "UNAVAILABLE",
    mobile: "9876543229",
  },
  {
    id: 21,
    name: "Siddharth Pandey",
    bloodGroup: "A+",
    region: "North",
    district: "District 3",
    status: "AVAILABLE",
    mobile: "9876543230",
  },
  {
    id: 22,
    name: "Rashmi Jain",
    bloodGroup: "O-",
    region: "South",
    district: "District 1",
    status: "UNAVAILABLE",
    mobile: "9876543231",
  },
  {
    id: 23,
    name: "Vikas Choudhary",
    bloodGroup: "B+",
    region: "East",
    district: "District 2",
    status: "AVAILABLE",
    mobile: "9876543232",
  },
  {
    id: 24,
    name: "Nalini Agarwal",
    bloodGroup: "AB-",
    region: "West",
    district: "District 3",
    status: "UNAVAILABLE",
    mobile: "9876543233",
  },
  {
    id: 25,
    name: "Rajiv Kumar",
    bloodGroup: "O+",
    region: "North",
    district: "District 1",
    status: "AVAILABLE",
    mobile: "9876543234",
  },
  {
    id: 26,
    name: "Sonal Mehta",
    bloodGroup: "A-",
    region: "South",
    district: "District 2",
    status: "UNAVAILABLE",
    mobile: "9876543235",
  },
  {
    id: 27,
    name: "Rahul Bhatia",
    bloodGroup: "B-",
    region: "East",
    district: "District 3",
    status: "AVAILABLE",
    mobile: "9876543236",
  },
  {
    id: 28,
    name: "Anushka Singh",
    bloodGroup: "AB+",
    region: "West",
    district: "District 1",
    status: "UNAVAILABLE",
    mobile: "9876543237",
  },
  {
    id: 29,
    name: "Sachin Goyal",
    bloodGroup: "A+",
    region: "North",
    district: "District 2",
    status: "AVAILABLE",
    mobile: "9876543238",
  },
  {
    id: 30,
    name: "Priyanka Chawla",
    bloodGroup: "O-",
    region: "South",
    district: "District 3",
    status: "UNAVAILABLE",
    mobile: "9876543239",
  },
];

module.exports = { data: sampleListings };
